---
title: "Desafios"
author: "Daniel Salgado"
date: "26/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Desafió de Aguas venenosas

### Desafió para hacerla de jamón

### Desafío El Seductor Canto de las Sirenas

***
Malas noticias, estás pres@ en una isla muy lejana, no te angusties, tienes una computadora, internet, comida y asilo. Tu carcelero ha accedido a darte una oportunidad: para salir tienes que resolver tres desafíos, así que sólo tu astucia puede salvarte de quedar, para siempre, aislado. 

Los desafíos no están ordenados por orden de dificultad, así que procura leerlos y luego resolverlos en el orden que te sea más cómodo.

Tu carcelero es un barbaján muy listo y sobretodo curioso así que si te sirves de dibujos, mapas mentales, ecuaciones, diagramas de flujo, etc, para encontrar una solución a los desafíos o bien para explicarla, ¡adelante! Te aceptará screenshots, fotos del pizarrón de tu celda o de dibujos de tu cuaderno. No tienes restricciones sobre el formato de respuesta de tus soluciones a los desafíos, salvo para los archivos, de preferencia envíalos en formato CSV.

¡Buena suerte! Recuerda que tu astucia es la llave de tu libertad.
***
